### ISSUE TITLE
[question] about async sequences

### ISSUE THREAD

**Issue by giuliohome** [Zaid-Ajaj/ElmCounterWPF#2]
A question more on the elmish side of things (I don't care about the WPF details).
I've tried to implement a command to produce a sequence of async actions: let's imagine incrementing the counter 10 times.
Now one usually wants to send progress updates to the UI saying for example: we are at step 7 of 10...
Is there a way to schedule a sequence of messages which would trigger such UI little updates (usually in WPF it could be implemented by a classical progress bar).
Yes I've seen that I can do like [here](https://github.com/giuliohome/ElmCounterWPF/blob/master/ElmCounter/Program.fs#L73-L78) with a sort of "_recursive_" function. But it is very counter intuitive and it starts to be easily unmanageable when the complexity of the app logic grows a bit... 

Which is the correct elmish way of producing progress updates?

**Comment by Zaid-Ajaj** [comment]
I see you are on the right path, you implemented some ping/pong logic with message passing. I think the limitation you are encountering is the from the fact that `Cmd.ofAsync` can dispatch only 1 message at a time. The simplest thing to do in the scenario is to implement your own command that is able to dispatch multiple messages at different times (i.e. you do the scheduling) : 
```fs
let asyncSeqEvery milliseconds (messages: Msg list) : Cmd<Msg> = 
  [ fun (dispatch: 'Msg -> unit) -> 
        async {
           for msg in messages do 
               do! Async.Sleep milliseconds 
               dispatch msg
        } |> Async.StartImmediate ] 

// then you can use it like this: 
StartSeqMsgs -> state, asyncSeqEvery 1000 [Increment; Increment; Increment]

```
This is already kind of advanced stuff in Elmish but I think you will understand: the type `Cmd<'t>` is the following:
```fs
type Dispatcher<'Msg> = 'Msg -> unit
type Cmd<'Msg> = (Dispatcher<'Msg> -> unit) list
```
Ofcourse, here you decide when the progress is going forward, but usually you don't know when some operation is finished and here is where [subscriptions](https://github.com/elmish/Elmish.WPF/blob/master/src/Samples/SubModel/Program.fs#L110-L120) come into play. They can be used to subscribe to events (clock tick, web socket connection etc.) and dispatch messages from the events. 

Anything unclear here? let me know!

**Comment by giuliohome** [comment]
Excellent answer! 
Exactly what I needed: 
I have a lot to study now...
